# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlLogz < Formula
  desc "Kubectl logs."
  homepage "https://github.com/kubectl-logz/kubectl-logz"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubectl-logz/kubectl-logz/releases/download/v0.0.5/kubectl-logz_0.0.5_Darwin_arm64.tar.gz"
      sha256 "627467a5dc0bbdc66623ed9d70fe8ee508fe46c1531075636d9a0a15f777d2ff"

      def install
        bin.install "kubectl-logz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubectl-logz/kubectl-logz/releases/download/v0.0.5/kubectl-logz_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "2c8af40ef7ec8ddb217417ac736414ebae3116c7284d970c2d8a2ff306a4190d"

      def install
        bin.install "kubectl-logz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubectl-logz/kubectl-logz/releases/download/v0.0.5/kubectl-logz_0.0.5_Linux_arm64.tar.gz"
      sha256 "3b4acf4870e57a87c00358de5264920909c9b1886c38ae8750ace5da33fe1c29"

      def install
        bin.install "kubectl-logz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubectl-logz/kubectl-logz/releases/download/v0.0.5/kubectl-logz_0.0.5_Linux_x86_64.tar.gz"
      sha256 "8379ae07669032ca9a82c85134790db32f030b8d515d028d93442f8468f50826"

      def install
        bin.install "kubectl-logz"
      end
    end
  end
end
